### PR TITLE
[Allowed to merge] First step of the new maps's folder. 

### PR DESCRIPTION
**Pull request by Xindage**
This commit show how we can order the map wads in the attic.

WIP commit and i'm still doing it, you guy can see what changed to see how I'm planning the maps folder.

### CODE REVIEW

**Comment by Xindage** [comment]
i just forget to save the changes of the phase 2 authors on this commit. nothing so major, it'll be present on next commit.

**Comment by Xindage** [comment]
Ready for merge, new levels from now on can use that folder, so it's easy to test or see the contents of each file, and the new authors.txt reveals who did each wad.

Future entryes must keep the alphabetical order of the author even if the entry is out of it. Ex:
entry023 - Aline
entry024 - Balco
entry030 - Celia
entry025 - Denis

It prevent the author file of being messes up babl on future editions.

**Comment by mc776** [comment]
When I was trying to think of a solution I tried to use dates, or commits, or some other way to come up with unique IDs.

Numbering by sequence like here seems to be a much better solution.

**Comment by Xindage** [comment]
you prefer it to be ordered by the entry id instead the alphabetical order?

Edit: i dont plan to keep the track of each date, so ordering by entry nunber is going to be way messy than alphabetical, i'm really sure of it.

**Comment by mc776** [comment]
I meant the way you had it here was better than what I had in mind.

**Pull request closed without merging**
