### PR TITLE
New stuff

### PR DESCRIPTION
**Pull request by GeorgePieVG**
- Lots of sprites and patches by CWolf as well as other Doomworld members. 

- Sodaholic has been renamed to Blastfrog
- Fixed some credits
- Added definitions for original textures
- Older versions of lavamander and octaminator

- Dave3D music, which was replaced a long time ago

### CODE REVIEW

**Comment by Xindage** [comment]
I dont think we should add stuff that was not directly for freedoom.

**Comment by GeorgePieVG** [comment]
> I dont think we should add stuff that was not directly for freedoom.

In that case, from Demon Eclipse, I can only keep the extended sprites for super shotgun and SKAG/BFG that have already been in Freedoom. I can also remove the wool ball enemies, though it's a shame the idea of using them was forgotten. I think it's worth keeping the text files with permission, in case we need these things in the future.

**Comment by GeorgePieVG** [comment]
Just cleaned up the PR. I think I took out all the unrelated stuff.

**Comment by Xindage** [comment]
good to merge?

**Comment by GeorgePieVG** [comment]
I think so.

**Pull request merged**
