### PR TITLE
Reorganize the attic + very big update

### PR DESCRIPTION
**Pull request by GeorgePieVG**
UPD: in the last commit, I redid the structure of the whole repository, now everything is made much more convenient. However, if you are not ready to merge this yet, I can drop the commit.

What's added:

- Monsters, including offsets:
- - Dark soldier
- - Pre-recolor combat slug and technospider
- - Deadflare
- - Summoner
- - Old player-like chaingunner
- - Old boots zombieman
- - Old player
- - lokito's old baron from 0.11
- - First version of zombieman
- - First version of demon by ScubaSteve

- All weapons from 0.12.1
- All previously featured music from 0.12.1 and 0.13.0
- Some levels from 0.12.1 and older, unaltered Double Impact
- A lot of sprites and patches from 0.12.1 and older

- Some stuff that was rejected or replaced between releases and never saw the light of day:
- - Tech pillar sketches from [comments on the pull request](https://github.com/freedoom/freedoom/pull/1180)
- - Korp's older patches
- - Dark soldier's more brutal death
- - Gilded Pain Lord by HorrorMovieRei
- - Music by J.Astartes (I love these tracks!)

- Restored some text files

### CODE REVIEW

**Comment by Xindage** [comment]
i'll review this pr when home so i can see the changes more precisely

**Comment by GeorgePieVG** [comment]
Just want to clarify, is it ok to take resources from comments on pull requests and add them to attic? Or does it require additional permission from the authors? I'm asking because I've already added a few.

**Comment by Xindage** [comment]
this is more of a question for @fragglet but as soon something goes into the PR candidates i think its because you wanna submit it in the project so you're giving us permission to use or not it, so i think its ok.

**Comment by Xindage** [comment]
Ok george i checked this myself now and it's indeed better in my opinion, it may conflict with my own PR too but it's not big deal, i'll still wait for 24h before committing this in case something need to be done before

**Comment by Xindage** [comment]
actually @GeorgePieVG do you think you can merge my own level System in your PR as well in some way, otherwise i can do it later.

**Comment by GeorgePieVG** [comment]
> actually @GeorgePieVG do you think you can merge my own level System in your PR as well in some way, otherwise i can do it later.

I can do that, but I have a question regarding the implementation of your PR. Should I delete the levels folder or create symlinks in your maps folder pointing to levels?

**Comment by Xindage** [comment]
Ok i think its time to metge since youre maintaining it.

**Pull request merged**
